### ISSUE TITLE
代码错误

### ISSUE THREAD

**Issue by CastleDream** [Wslsdx/Deep-Learning-Approach-for-Surface-Defect-Detection#13]
model.py中，self__learn_rate和self.is_training写重复了两次
def __init__(self,sess,param):
        self.step = 0
        self.__session = sess
        **self.is_training=True**
        **self.__learn_rate = param["learn_rate"]
        self.__learn_rate=param["learn_rate"]**
        self.__max_to_keep=param["max_to_keep"]
        self.__checkPoint_dir = param["checkPoint_dir"]
        self.__restore = param["b_restore"]
        self.__mode= param["mode"]
        **self.is_training=True**
        self.__batch_size = param["batch_size"]
        if  self.__mode is "savaPb" :
            self.__batch_size = 1

**Comment by Wslsdx** [comment]
Thanks!

**Comment by ShuaiLYU** [comment]
@CastleDream  Thanks！
