### ISSUE TITLE
CVPR2019?

### ISSUE THREAD

**Issue by figkim** [Wslsdx/Deep-Learning-Approach-for-Surface-Defect-Detection#2]
@Wslsdx  Thx for your implementation!
However, is this paper accepted to cvpr2019? I cannot find the name of this paper in the accepted paper list. In both of [(oral)](https://github.com/hoya012/CVPR-2019-Paper-Statistics/blob/master/2019_cvpr/cvpr_2019_oral.csv)[(poster)](https://github.com/hoya012/CVPR-2019-Paper-Statistics/blob/master/2019_cvpr/cvpr_2019_poster.csv).

**Comment by Wslsdx** [comment]
Thanks for your reminding me ! I got this paper from here[ https://arxiv.org/abs/1903.08536].  I think the author submitted the paper to cvpr2019 but it was not accepted. I will correct the ReadMe.

**Comment by skokec** [comment]
Hi! As the author of this paper I would just like to correct you that this work was never submitted to CVPR but only to Journal of Intelligent Manufacturing (https://link.springer.com/article/10.1007/s10845-019-01476-x), where it was published last month. I would kindly ask to cite that paper when using this model and dataset.

**Comment by ShuaiLYU** [comment]
I am  so sorry for the mistake. I 'll correct it right away .   Your papar is  amazing and It's a pleasure to follow your work!

**Comment by figkim** [comment]
@skokec @Wslsdx Thx for the confirmation! It was not meant to be attacked at all, just to make sure the information. It would be better to close the issue. BTW appreciate for your works, both of you!

**Comment by loveq007** [comment]
> Hi! As the author of this paper I would just like to correct you that this work was never submitted to CVPR but only to Journal of Intelligent Manufacturing (https://link.springer.com/article/10.1007/s10845-019-01476-x), where it was published last month. I would kindly ask to cite that paper when using this model and dataset.

@skokec Hi, I have one question about the proposed segmentation network in your paper: the output-map resolution was reduced by 8 times, how it can compare with U-Net and Deeplabv3+(Output full resolution map) in Fig13 Fig14? Or how to achieve those image results?

**Comment by skokec** [comment]
Hi @loveq007, for U-Net and DeepLab we got full resolution output first, then downsampled the it using the avg_pool2d (with kernel_size=17 and stride=8) obly before passing it to the loss, but we passed full resolution into the second stage. Outputs in Fig13 and Fig14 are then the display of U-Net/DeepLab output before applying avg_pool2d.
