### ISSUE TITLE
Difference with official repository?

### ISSUE THREAD

**Issue by JulienMaille** [Wslsdx/Deep-Learning-Approach-for-Surface-Defect-Detection#9]
No offense but may I ask what are the differences with the author repository? https://github.com/skokec/segdec-net-jim2019
Did I missed something?

**Comment by Wslsdx** [comment]
@neFAST       I reproduced the experiment from the paper And I  built this repository before the author .  U can compare the two repositorys .

**Comment by ShuaiLYU** [comment]
@neFAST   I reproduced the experiment from the paper and  built this repository before the author . U can compare the two .

**Comment by JulienMaille** [comment]
I've tried putting everything in a Google Colab notebook but training looks abnormally slow and generates a lot of warnings. Did I do something wrong?
https://colab.research.google.com/drive/1SvX85g0EjWUztkx2JrLxc6derc6baP4q
